
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Runtime.Serialization;

namespace Softv.Entities
{
    /// <summary>
    /// Class                   : Softv.Entities.TerminalEntity.cs
    /// Generated by            : Class Generator (c) 2014
    /// Description             : Terminal entity
    /// File                    : TerminalEntity.cs
    /// Creation date           : 18/02/2017
    /// Creation time           : 01:21 p. m.
    ///</summary>
    [DataContract]
    [Serializable]
    public class TerminalEntity : BaseEntity
    {
        #region Attributes

        /// <summary>
        /// Property SAN
        /// </summary>
        [DataMember]
        public long? SAN { get; set; }
        /// <summary>
        /// Property IdSuscriptor
        /// </summary>
        [DataMember]
        public long? IdSuscriptor { get; set; }
        /// <summary>
        /// Property IdServicio
        /// </summary>
        [DataMember]
        public int? IdServicio { get; set; }
        /// <summary>
        /// Property Latitud
        /// </summary>
        [DataMember]
        public String Latitud { get; set; }
        /// <summary>
        /// Property Longitud
        /// </summary>
        [DataMember]
        public String Longitud { get; set; }
        /// <summary>
        /// Property Estatus
        /// </summary>
        [DataMember]
        public String Estatus { get; set; }
        /// <summary>
        /// Property FechaAlta
        /// </summary>
        [DataMember]
        public String FechaAlta { get; set; }
        /// <summary>
        /// Property FechaSuspension
        /// </summary>
        [DataMember]
        public String FechaSuspension { get; set; }
        /// <summary>
        /// Property ESN
        /// </summary>
        [DataMember]
        public String ESN { get; set; }
        /// <summary>
        /// Property Comentarios
        /// </summary>
        [DataMember]
        public String Comentarios { get; set; }

        [DataMember]
        public String Servicio { get; set; }

        [DataMember]
        public String Suscriptor { get; set; }


        [DataMember]
        public int? Op { get; set; }



        [DataMember]
        public String SatellitedID { get; set; }

        [DataMember]
        public int? BeamID { get; set; }

        [DataMember]
        public String Polarization { get; set; }

        [DataMember]
        public String Referencia { get; set; }


        #endregion
    }
}

