
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Runtime.Serialization;

namespace Softv.Entities
{
    /// <summary>
    /// Class                   : Softv.Entities.UsuarioSystemEntity.cs
    /// Generated by            : Class Generator (c) 2014
    /// Description             : UsuarioSystem entity
    /// File                    : UsuarioSystemEntity.cs
    /// Creation date           : 18/02/2017
    /// Creation time           : 01:32 p. m.
    ///</summary>
    [DataContract]
    [Serializable]
    public class UsuarioSystemEntity : BaseEntity
    {
        #region Attributes

        /// <summary>
        /// Property IdUsuario
        /// </summary>
        [DataMember]
        public int? IdUsuario { get; set; }
        /// <summary>
        /// Property IdTipoUsuario
        /// </summary>
        [DataMember]
        public int? IdTipoUsuario { get; set; }
        /// <summary>
        /// Property Nombre
        /// </summary>
        [DataMember]
        public String Nombre { get; set; }
        /// <summary>
        /// Property Email
        /// </summary>
        [DataMember]
        public String Email { get; set; }
        /// <summary>
        /// Property Password
        /// </summary>
        [DataMember]
        public String Password { get; set; }

        #endregion
    }
}

