
using System;
using System.Collections.Generic;
using System.Text;
using System.Data;
using System.ComponentModel;
using System.Linq;
using Softv.Providers;
using Softv.Entities;
using Globals;

/// <summary>
/// Class                   : Softv.BAL.Client.cs
/// Generated by            : Class Generator (c) 2014
/// Description             : SecutityBussines
/// File                    : SecutityBussines.cs
/// Creation date           : 14/12/2015
/// Creation time           : 11:51 a. m.
///</summary>
namespace Softv.BAL
{

    [DataObject]
    [Serializable]
    public class Secutity
    {

        #region Constructors
        public Secutity() { }
        #endregion

        /// <summary>
        ///Adds Secutity
        ///</summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
        public static int Add(SecutityEntity objSecutity)
        {
            int result = ProviderSoftv.Secutity.AddSecutity(objSecutity);
            return result;
        }

        /// <summary>
        ///Delete Secutity
        ///</summary>
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public static int Delete(int? IdSecutity)
        {
            int resultado = ProviderSoftv.Secutity.DeleteSecutity(IdSecutity);
            return resultado;
        }

        /// <summary>
        ///Update Secutity
        ///</summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
        public static int Edit(SecutityEntity objSecutity)
        {
            int result = ProviderSoftv.Secutity.EditSecutity(objSecutity);
            return result;
        }

        /// <summary>
        ///Get Secutity
        ///</summary>
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public static List<SecutityEntity> GetAll()
        {
            List<SecutityEntity> entities = new List<SecutityEntity>();
            entities = ProviderSoftv.Secutity.GetSecutity();

            return entities ?? new List<SecutityEntity>();
        }

        /// <summary>
        ///Get Secutity List<lid>
        ///</summary>
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public static List<SecutityEntity> GetAll(List<int> lid)
        {
            List<SecutityEntity> entities = new List<SecutityEntity>();
            entities = ProviderSoftv.Secutity.GetSecutity(lid);
            return entities ?? new List<SecutityEntity>();
        }

        /// <summary>
        ///Get Secutity By Id
        ///</summary>
        [DataObjectMethod(DataObjectMethodType.Select)]
        public static SecutityEntity GetOne(int? IdSecutity)
        {
            SecutityEntity result = ProviderSoftv.Secutity.GetSecutityById(IdSecutity);

            return result;
        }

        /// <summary>
        ///Get Secutity By Id
        ///</summary>
        [DataObjectMethod(DataObjectMethodType.Select)]
        public static SecutityEntity GetOneDeep(int? IdSecutity)
        {
            SecutityEntity result = ProviderSoftv.Secutity.GetSecutityById(IdSecutity);

            return result;
        }



        /// <summary>
        ///Get Secutity
        ///</summary>
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public static SoftvList<SecutityEntity> GetPagedList(int pageIndex, int pageSize)
        {
            SoftvList<SecutityEntity> entities = new SoftvList<SecutityEntity>();
            entities = ProviderSoftv.Secutity.GetPagedList(pageIndex, pageSize);

            return entities ?? new SoftvList<SecutityEntity>();
        }

        /// <summary>
        ///Get Secutity
        ///</summary>
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public static SoftvList<SecutityEntity> GetPagedList(int pageIndex, int pageSize, String xml)
        {
            SoftvList<SecutityEntity> entities = new SoftvList<SecutityEntity>();
            entities = ProviderSoftv.Secutity.GetPagedList(pageIndex, pageSize, xml);

            return entities ?? new SoftvList<SecutityEntity>();
        }


    }




    #region Customs Methods

    #endregion
}
